# app/models/ai_task_suggestion.py
# --------------------------------------------------------------------------------
# Establishes the database model to store raw Gemini AI task suggestions.
# This acts as an audit trail of AI recommendations and allows PM validation.
# --------------------------------------------------------------------------------

from sqlalchemy import Column, ForeignKey, Integer, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.mixins import TimestampMixin


class AITaskSuggestion(TimestampMixin, Base):
    # Maps class to the 'ai_task_suggestions' table in database
    __tablename__ = "ai_task_suggestions"

    # Unique identification number for every suggestion log row
    id = Column(Integer, primary_key=True, index=True)
    
    # Points to parent requirement ID to connect AI suggestions with requirement details
    requirement_id = Column(
        Integer, ForeignKey("requirements.id"), nullable=False, index=True
    )

    # Stores the raw JSON response containing the suggested tasks array directly from Gemini
    generated_tasks_json = Column(JSONB, nullable=False)

    # Optional overall risks generated by AI for the requirement
    risks = Column(Text, nullable=True)
    
    # Optional overall QA acceptance criteria suggested by AI
    acceptance_criteria = Column(Text, nullable=True)

    # Defines the relationship with Requirement model to easily fetch parent requirement data
    requirement = relationship("Requirement", back_populates="ai_suggestions") #An ORM helper that links Python objects together.

    def __repr__(self):
        # Python representation to print friendly identifier when logging
        return f"<AITaskSuggestion id={self.id} requirement_id={self.requirement_id}>"
