# app/models/task.py
# --------------------------------------------------------------------------------
# Establishes the database model for Tasks.
# This is the core transactional object updated by PMs, developers, and testers.
# --------------------------------------------------------------------------------

from sqlalchemy import Column, Date, Float, ForeignKey, Integer, String, Text, Boolean
from sqlalchemy.orm import relationship

from app.core.database import Base
from app.models.mixins import TimestampMixin


class Task(TimestampMixin, Base):
    # Maps class to 'tasks' table in database
    __tablename__ = "tasks"

    # Unique identification number for the task card
    id = Column(Integer, primary_key=True, index=True)

    # ── Foreign keys ───────────────────────────────────────────────────────
    
    # Points to parent project that owns this task
    project_id     = Column(Integer, ForeignKey("projects.id"),      nullable=False)
    
    # Points to scheduled sprint cycle (Null means it rests in the Backlog)
    sprint_id      = Column(Integer, ForeignKey("sprints.id"),       nullable=True)
    
    # Optional link to parent product requirement description
    requirement_id = Column(Integer, ForeignKey("requirements.id"),  nullable=True)
    
    # References the user account (Developer or Tester) assigned to execute this task
    assignee_id    = Column(Integer, ForeignKey("users.id"),         nullable=True)
    
    # References user profile (PM/Admin) who created this task card
    created_by     = Column(Integer, ForeignKey("users.id"),         nullable=True)

    # ── Core fields ────────────────────────────────────────────────────────
    
    # Headline text representing the task goal (maximum of 250 characters)
    title            = Column(String(250), nullable=False)
    
    # Detailed technical guidelines or description details for the task
    description      = Column(Text,        nullable=True)
    
    # Task type classification: development, testing, bug, documentation
    task_type        = Column(String(20),   nullable=False)
    
    # Priority classification: low, medium, high, critical
    priority         = Column(String(10),   nullable=False)
    
    # Current execution status state: TODO, IN_PROGRESS, IN_REVIEW, DONE
    status           = Column(String(20),   nullable=False, default="TODO")
    
    # Target deadline date for the task completion
    due_date         = Column(Date,         nullable=True)
    
    # Time estimate in hours
    estimated_hours  = Column(Float,        nullable=True)
    
    # Soft delete toggle: prevents records from hard deletion, protecting database history
    is_deleted       = Column(Boolean,      default=False, nullable=False)

    # ── AI Generated Metadata fields ──────────────────────────────────────
    
    # Story points or effort estimation (used in Sprint report calculations)
    effort_points        = Column(Integer, nullable=True)
    
    # Specific QA parameters required to mark the task completed
    acceptance_criteria  = Column(Text,    nullable=True)
    
    # Warning details generated by Gemini AI during task creation
    risk_notes           = Column(Text,    nullable=True)

    # ── Relationships ──────────────────────────────────────────────────────
    
    # Link to parent project model
    project     = relationship("Project",     back_populates="tasks")
    
    # Link to scheduled sprint model
    sprint      = relationship("Sprint",      back_populates="tasks")
    
    # Link to parent requirement model
    requirement = relationship("Requirement", back_populates="tasks")
    
    # Link to user profile assigned to the task
    assignee    = relationship("User", back_populates="tasks_assigned",  foreign_keys=[assignee_id])
    
    # Link to user profile who created the task
    creator     = relationship("User", back_populates="tasks_created",   foreign_keys=[created_by])
    
    # Link to comments log. Cascade deletes comments if the parent task is deleted
    comments    = relationship("TaskComment", back_populates="task", cascade="all, delete-orphan")

    def __repr__(self):
        # Python representation to print friendly identifier when logging
        return (
            f"<Task id={self.id} title={self.title!r} "
            f"status={self.status!r} priority={self.priority!r}>"
        )
