# app/routers/ai_routes.py
# --------------------------------------------------------------------------------
# Defines AI-powered task breakdown and confirmation API endpoints.
# This router communicates with AIService and converts suggestions to actual tasks.
# Restricted to Admin (1) and Project Manager (2) roles.
# --------------------------------------------------------------------------------

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from typing import Optional
from sqlalchemy.orm import Session

from app.core.database import get_db
from app.core.security import require_role
from app.repositories import requirement_repo, task_repo, sprint_repo
from app.models.ai_task_suggestion import AITaskSuggestion
from app.schemas.common import APIResponse
from app.services.ai_service import AIService

# Set up router path configuration
router = APIRouter(prefix="/ai", tags=["AI"])


# ── Pydantic Request schemas ──────────────────────────────────────────────────

class TaskBreakdownRequest(BaseModel):
    """Input payload validation for generating task suggestions from a requirement."""
    requirement_id: int
    requirement_title: str
    requirement_description: str
    expected_output: Optional[str] = None


class ConfirmTaskItem(BaseModel):
    """Represents a single task generated by AI to be confirmed and saved."""
    title: str
    description: Optional[str] = None
    task_type: str
    priority: str
    effort_points: Optional[int] = None
    acceptance_criteria: Optional[str] = None
    possible_risks: Optional[str] = None
    assignee_id: Optional[int] = None
    status: str = "todo"


class ConfirmTasksRequest(BaseModel):
    """Payload sent by frontend containing list of confirmed tasks to write to database."""
    suggestion_id: int
    sprint_id: Optional[int] = None
    tasks: list[ConfirmTaskItem]


# ── POST /ai/task-breakdown ───────────────────────────────────────────────────

@router.post("/task-breakdown", response_model=APIResponse)
def generate_task_breakdown(
    payload: TaskBreakdownRequest,
    db: Session = Depends(get_db),
    current_user=Depends(require_role(1, 2)),  # Gated to PM/Admin only
):
    """
    POST /ai/task-breakdown
    Triggers the Gemini model to parse the requirement description into structured tasks.
    Saves raw suggested values to 'ai_task_suggestions' table for auditing logs.
    """
    # 1. Verify parent requirement model is present
    requirement = requirement_repo.get_requirement_by_id(db, payload.requirement_id)
    if not requirement:
        raise HTTPException(status_code=404, detail="Requirement not found.")

    # 2. Call AI service to query Google Gemini
    ai_result = AIService.generate_task_breakdown(
        title=payload.requirement_title,
        description=payload.requirement_description,
        expected_output=payload.expected_output,
    )

    # 3. Create suggestion log instance to save raw prompt results in DB
    suggestion = AITaskSuggestion(
        requirement_id=payload.requirement_id,
        generated_tasks_json=ai_result["tasks"],
        # Combine list of risks into a single semi-colon separated string
        risks="; ".join(
            t.get("possible_risks", "") for t in ai_result["tasks"] if t.get("possible_risks")
        ) or None,
        # Combine list of acceptance criteria sentences
        acceptance_criteria="; ".join(
            t.get("acceptance_criteria", "") for t in ai_result["tasks"] if t.get("acceptance_criteria")
        ) or None,
    )
    db.add(suggestion)
    db.commit()
    db.refresh(suggestion)

    # 4. Return results for PM display and review
    return APIResponse.ok(
        data={
            "suggestion_id": suggestion.id,
            "summary": ai_result["summary"],
            "tasks": ai_result["tasks"],
        },
        message="Tasks generated successfully.",
    )


# ── POST /ai/confirm-tasks ───────────────────────────────────────────────────

@router.post("/confirm-tasks", response_model=APIResponse)
def confirm_ai_tasks(
    payload: ConfirmTasksRequest,
    db: Session = Depends(get_db),
    current_user=Depends(require_role(1, 2)),  # Gated to PM/Admin only
):
    """
    POST /ai/confirm-tasks
    Saves PM-confirmed/edited task recommendations into the actual tasks database table.
    """
    # 1. Fetch raw suggestion record to identify project/requirement link
    suggestion = db.query(AITaskSuggestion).filter(
        AITaskSuggestion.id == payload.suggestion_id
    ).first()
    if not suggestion:
        raise HTTPException(status_code=404, detail="AI suggestion not found.")

    requirement = requirement_repo.get_requirement_by_id(db, suggestion.requirement_id)
    if not requirement:
        raise HTTPException(status_code=404, detail="Requirement not found.")

    project_id = requirement.project_id

    # 2. Verify target sprint state allows new additions
    if payload.sprint_id:
        sprint = sprint_repo.get_sprint_by_id(db, payload.sprint_id)
        if not sprint:
            raise HTTPException(status_code=404, detail="Sprint not found.")
        if sprint.status.lower() not in ["planning", "active"]:
            raise HTTPException(
                status_code=400,
                detail="Tasks can only be added to sprints in 'planning' or 'active' status.",
            )

    # 3. Create each task item in db using repository creation calls
    created_tasks = []
    for task_item in payload.tasks:
        task_data = {
            "project_id": project_id,
            "sprint_id": payload.sprint_id,
            "requirement_id": suggestion.requirement_id,
            "title": task_item.title,
            "description": task_item.description,
            "task_type": task_item.task_type,
            "priority": task_item.priority,
            "status": task_item.status or "todo",
            "effort_points": task_item.effort_points,
            "acceptance_criteria": task_item.acceptance_criteria,
            "risk_notes": task_item.possible_risks,
            "assignee_id": task_item.assignee_id,
            "created_by": current_user.id,
        }
        task = task_repo.create_single_task(db, task_data)
        created_tasks.append({
            "id": task.id,
            "title": task.title,
        })

    return APIResponse.ok(
        data={"tasks": created_tasks},
        message=f"{len(created_tasks)} tasks saved successfully.",
    )
