"""update requirement

Revision ID: 141705775b79
Revises: b2c3d4e5f6a7
Create Date: 2026-06-30 17:28:29.976210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '141705775b79'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('priority', sa.String(length=10), nullable=False, server_default='medium'))
    op.add_column('requirements', sa.Column('acceptance_criteria', sa.Text(), nullable=True))
    op.drop_column('requirements', 'expected_output')
    op.drop_column('requirements', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('requirements', sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('requirements', 'acceptance_criteria')
    op.drop_column('requirements', 'priority')
    # ### end Alembic commands ###
