"""Add status to requirement

Revision ID: d2aeee9e1324
Revises: 863808968641
Create Date: 2026-07-05 13:13:29.004697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2aeee9e1324'
down_revision: Union[str, None] = '863808968641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('status', sa.String(length=20), server_default='DRAFT', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'status')
    # ### end Alembic commands ###
