// src/pages/CreateRequirementPage.jsx
// =============================================================================
// "New Requirement" page — with AI-powered task breakdown.
//
// FLOW:
//  Section 1:  Fill requirement details → click "Save & Add Tasks" or "Save & Generate with AI"
//  Section AI: (After save + AI) Review, edit, and confirm AI-generated tasks
//  Section 2:  (After save) Manually add tasks one-by-one (always available)
//
// The AI flow:  React → FastAPI → Gemini API → FastAPI → React
// The AI API key is NEVER in frontend code. Only the backend knows it.
// =============================================================================..

import { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import { createRequirement } from '../api/requirements';
import { getProjects } from '../api/projects';
import { getSprints } from '../api/sprint';
import { createSingleTask } from '../api/tasks';
import { generateTaskBreakdown, confirmAITasks } from '../api/ai';
import { getTeamUsers } from '../api/auth';
import { getUser, formatDate, priorityClass, getErrorMessage } from '../utils/helpers';
import { PRIORITY_OPTIONS, TASK_TYPE_OPTIONS, EFFORT_OPTIONS } from '../utils/constants';

/**
 * CreateRequirementPage Component
 * --------------------------------------------------------------------------------
 * Allows product managers or admins to define requirements, save them to the DB,
 * and then trigger an AI workflow that breaks requirements into backlog tasks,
 * or add tasks manually.
 * --------------------------------------------------------------------------------
 */
export default function CreateRequirementPage() {
    const navigate = useNavigate();
    const currentUser = getUser();

    // ── Projects & Sprints State ──
    const [projects, setProjects] = useState([]);                  // System projects list
    const [sprints, setSprints] = useState([]);                    // Project sprints list
    const [teamUsers, setTeamUsers] = useState([]);                // Assignee users list
    const [loadingProjects, setLoadingProjects] = useState(true);   // Loader state for fetching project details

    // ── Section 1: Requirement Form States ──
    const [reqForm, setReqForm] = useState({
        project_id: '',
        title: '',
        description: '',
        priority: 'medium',
        acceptance_criteria: '',
    });
    const [reqErrors, setReqErrors] = useState({});                // Form validation error highlights
    const [reqSubmitting, setReqSubmitting] = useState(false);      // Saves loading spinner indicator
    const [reqMsg, setReqMsg] = useState('');                      // Form success banners

    // ── Section 2: Post-Save States ──
    const [savedRequirement, setSavedRequirement] = useState(null); // Saved requirement response from DB
    const [showTaskSection, setShowTaskSection] = useState(false);  // Toggles the manual task creation section

    // ── Section 2: Task Form States (Manual Quick-Add) ──
    const [taskForm, setTaskForm] = useState({
        title: '',
        description: '',
        task_type: 'development',
        priority: 'medium',     // Defaults to the requirement's priority level
        sprint_id: '',
        assignee_id: '',
        due_date: '',
        estimated_hours: '',
    });
    const [taskErrors, setTaskErrors] = useState({});              // Task form validation errors
    const [taskSubmitting, setTaskSubmitting] = useState(false);    // Task saving indicator
    const [taskMsg, setTaskMsg] = useState('');                    // Task success notification
    const [createdTasks, setCreatedTasks] = useState([]);          // Tasks created manually in this session

    // ── AI Task Breakdown States ──
    const [aiLoading, setAiLoading] = useState(false);              // AI task breakdown loader
    const [aiError, setAiError] = useState('');                      // AI breakdown network errors
    const [aiTasks, setAiTasks] = useState([]);                      // Editable list of tasks generated by the AI
    const [aiSuggestionId, setAiSuggestionId] = useState(null);      // Suggestion ID token from backend
    const [aiSummary, setAiSummary] = useState('');                  // Summarized explanation from AI model
    const [showAIReview, setShowAIReview] = useState(false);        // Toggles displaying the review table
    const [aiConfirming, setAiConfirming] = useState(false);        // Confirms submit indicator
    const [aiConfirmMsg, setAiConfirmMsg] = useState('');            // Confirms success banner text
    const [aiConfirmError, setAiConfirmError] = useState('');        // Confirms error alerts
    const [aiSavedTasks, setAiSavedTasks] = useState([]);            // AI tasks successfully saved to DB

    // Modal states for editing a generated AI task in-place
    const [editingTaskIndex, setEditingTaskIndex] = useState(null);
    const [editingTaskData, setEditingTaskData] = useState(null);

    // ── Load initial projects & team members on page mount ──
    useEffect(() => {
        Promise.all([getProjects(), getTeamUsers()])
            .then(([projRes, usersRes]) => {
                const projs = projRes.data.data || [];
                setProjects(projs);
                setTeamUsers(usersRes.data.data || []);
                if (projs.length > 0) {
                    setReqForm(f => ({ ...f, project_id: String(projs[0].id) }));
                }
            })
            .catch(() => { })
            .finally(() => setLoadingProjects(false));
    }, []);

    // ── Load sprints whenever selected project ID changes ──
    useEffect(() => {
        if (!reqForm.project_id) { setSprints([]); return; }
        getSprints({ project_id: Number(reqForm.project_id) })
            .then(res => {
                const list = res.data.data || [];
                setSprints(list);
            })
            .catch(() => setSprints([]));
    }, [reqForm.project_id]);

    // ─────────────────────────────────────────────────────────────────────
    // Section 1: Requirement Detail Handlers
    // ─────────────────────────────────────────────────────────────────────

    /**
     * validateReqForm Function
     * Validates input values before posting requirement creation.
     */
    function validateReqForm() {
        const e = {};
        if (!reqForm.project_id) e.project_id = 'Please select a project.';
        if (!reqForm.title.trim()) e.title = 'Requirement title is required.';
        if (!reqForm.description.trim()) e.description = 'Description is required.';
        if (!reqForm.priority) e.priority = 'Priority is required.';
        return e;
    }

    /**
     * saveRequirement Function
     * Saves the requirement details. If openTasks is true, opens the manual task creator.
     * Otherwise, displays success notification and redirects back to requirements list.
     */
    async function saveRequirement(openTasks = false) {
        const errs = validateReqForm();
        if (Object.keys(errs).length) { setReqErrors(errs); return; }
        setReqSubmitting(true);
        setReqMsg('');
        try {
            const res = await createRequirement({
                project_id: Number(reqForm.project_id),
                title: reqForm.title.trim(),
                description: reqForm.description.trim(),
                priority: reqForm.priority,
                acceptance_criteria: reqForm.acceptance_criteria.trim() || null,
            });
            const req = res.data?.data;
            setSavedRequirement(req);
            setReqMsg('Requirement saved successfully!');

            if (openTasks) {
                // Prefill manual task priority state with requirement priority level
                setTaskForm(f => ({ ...f, priority: reqForm.priority }));
                setShowTaskSection(true);
                setCreatedTasks([]);
            } else {
                alert('Requirement saved successfully');
                navigate('/requirements');
            }
        } catch (err) {
            setReqErrors({ form: getErrorMessage(err) });
        } finally {
            setReqSubmitting(false);
        }
    }

    /**
     * saveAndGenerateAI Function
     * Saves requirement details first, then triggers the AI breakdown flow automatically.
     */
    async function saveAndGenerateAI() {
        const errs = validateReqForm();
        if (Object.keys(errs).length) { setReqErrors(errs); return; }
        setReqSubmitting(true);
        setReqMsg('');
        try {
            const res = await createRequirement({
                project_id: Number(reqForm.project_id),
                title: reqForm.title.trim(),
                description: reqForm.description.trim(),
                priority: reqForm.priority,
                acceptance_criteria: reqForm.acceptance_criteria.trim() || null,
            });
            const req = res.data?.data;
            setSavedRequirement(req);
            setReqMsg('Requirement saved! Generating tasks with AI…');
            setReqSubmitting(false);

            // Trigger AI generator with newly saved requirement
            handleGenerateAI(req);
        } catch (err) {
            setReqErrors({ form: getErrorMessage(err) });
            setReqSubmitting(false);
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // AI Task Generation Handlers
    // ─────────────────────────────────────────────────────────────────────

    /**
     * handleGenerateAI Function
     * Hits AI task breakdown router, parses suggestions, and renders review modal.
     */
    async function handleGenerateAI(requirement = null) {
        const req = requirement || savedRequirement;
        if (!req) return;

        setAiLoading(true);
        setAiError('');
        setAiTasks([]);
        setShowAIReview(false);
        setAiConfirmMsg('');
        setAiConfirmError('');
        setAiSavedTasks([]);

        try {
            const res = await generateTaskBreakdown({
                requirement_id: req.id,
                requirement_title: req.title,
                requirement_description: req.description,
                expected_output: req.acceptance_criteria || null,
            });

            const data = res.data?.data;
            setAiSuggestionId(data.suggestion_id);
            setAiSummary(data.summary || '');
            setAiTasks(data.tasks || []);
            setShowAIReview(true);
        } catch (err) {
            setAiError(getErrorMessage(err) || 'AI is currently unavailable. You can add tasks manually.');
        } finally {
            setAiLoading(false);
        }
    }

    /**
     * handleAITaskEdit Function
     * In-place updater for AI task list variables.
     */
    function handleAITaskEdit(index, field, value) {
        setAiTasks(prev => prev.map((t, i) =>
            i === index ? { ...t, [field]: value } : t
        ));
    }

    /**
     * handleRemoveAITask Function
     * Deletes a suggestion before save confirmation.
     */
    function handleRemoveAITask(index) {
        setAiTasks(prev => prev.filter((_, i) => i !== index));
    }

    /**
     * handleConfirmAITasks Function
     * Commits the reviewed AI suggestions to the database, linking them to backlog.
     */
    async function handleConfirmAITasks() {
        if (aiTasks.length === 0) {
            setAiConfirmError('No tasks to save. Add tasks manually or regenerate.');
            return;
        }

        setAiConfirming(true);
        setAiConfirmError('');
        setAiConfirmMsg('');

        try {
            const res = await confirmAITasks({
                suggestion_id: aiSuggestionId,
                sprint_id: null, // Initially assigned to backlog
                tasks: aiTasks.map(t => ({
                    title: t.title,
                    description: t.description || null,
                    task_type: t.task_type,
                    priority: t.priority,
                    effort_points: t.effort_points ? Number(t.effort_points) : null,
                    acceptance_criteria: t.acceptance_criteria || null,
                    possible_risks: t.possible_risks || null,
                    assignee_id: t.assignee_id ? Number(t.assignee_id) : null,
                    status: 'TODO',
                })),
            });

            const saved = res.data?.data?.tasks || [];
            setAiSavedTasks(saved);
            setAiConfirmMsg(`${saved.length} tasks saved to backlog!`);
            setShowAIReview(false);
            navigate('/backlog'); // Navigate to backlog view
        } catch (err) {
            setAiConfirmError(getErrorMessage(err));
        } finally {
            setAiConfirming(false);
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Section 2: Manual Task Creation Handlers
    // ─────────────────────────────────────────────────────────────────────

    function validateTaskForm() {
        const e = {};
        if (!taskForm.title.trim()) e.title = 'Task title is required.';
        if (!taskForm.task_type) e.task_type = 'Task type is required.';
        if (!taskForm.priority) e.priority = 'Priority is required.';
        return e;
    }

    /**
     * handleAddTask Function
     * Submits a manual task creation form to assign backlog or sprint tasks.
     */
    async function handleAddTask(e) {
        e.preventDefault();
        const errs = validateTaskForm();
        if (Object.keys(errs).length) { setTaskErrors(errs); return; }

        setTaskSubmitting(true);
        setTaskErrors({});
        setTaskMsg('');
        try {
            const res = await createSingleTask({
                project_id: Number(reqForm.project_id),
                sprint_id: taskForm.sprint_id ? Number(taskForm.sprint_id) : undefined,
                requirement_id: savedRequirement?.id || null,
                title: taskForm.title.trim(),
                description: taskForm.description.trim() || null,
                task_type: taskForm.task_type,
                priority: taskForm.priority,
                assignee_id: taskForm.assignee_id ? Number(taskForm.assignee_id) : null,
                due_date: taskForm.due_date || null,
                estimated_hours: taskForm.estimated_hours ? parseFloat(taskForm.estimated_hours) : null,
            });

            const newTask = res.data?.data;
            setCreatedTasks(prev => [newTask, ...prev]);
            setTaskMsg(`Task "${taskForm.title.trim()}" added!`);

            // Reset task form, retaining sprint choices and inheriting original priorities
            setTaskForm(f => ({
                title: '',
                description: '',
                task_type: 'development',
                priority: savedRequirement?.priority || 'medium',
                sprint_id: f.sprint_id,
                assignee_id: '',
                due_date: '',
                estimated_hours: '',
            }));
        } catch (err) {
            setTaskErrors({ form: getErrorMessage(err) });
        } finally {
            setTaskSubmitting(false);
        }
    }

    return (
        <div className="page page-wide requirement-page">
            {/* Title section */}
            <div className="page-header">
                <h1 className="page-title">New Requirement</h1>
                <p className="muted-sm" style={{ marginTop: 4 }}>
                    Define a requirement, then generate tasks with AI or add them manually.
                </p>
            </div>

            {/* ── STEP 1: Requirement Form / Details Summary ── */}
            <div className="card">
                <div className="card-header">
                    <h3 className="card-title">
                        {savedRequirement ? `✅ Requirement Saved: ${savedRequirement.title}` : 'Step 1: Requirement Details'}
                    </h3>
                </div>

                {savedRequirement ? (
                    <div style={{ padding: '4px 0 12px' }}>
                        <p className="muted-sm">
                            <strong>Project:</strong> {projects.find(p => p.id === savedRequirement.project_id)?.name || '—'} ·{' '}
                            <strong>Priority:</strong> <span className={`badge ${priorityClass(savedRequirement.priority)}`}>{savedRequirement.priority}</span>
                        </p>
                        {savedRequirement.acceptance_criteria && (
                            <p className="muted-sm" style={{ marginTop: 6 }}>
                                <strong>Acceptance Criteria:</strong> {savedRequirement.acceptance_criteria}
                            </p>
                        )}

                        <div style={{ display: 'flex', gap: 10, marginTop: 12, flexWrap: 'wrap' }}>
                            {/* AI Trigger */}
                            {!showAIReview && aiSavedTasks.length === 0 && (
                                <button
                                    className="btn btn-primary"
                                    disabled={aiLoading}
                                    onClick={() => handleGenerateAI()}
                                    style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', border: 'none' }}
                                >
                                    {aiLoading ? (
                                        <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                                            <span className="spinner" style={{ width: 16, height: 16, borderWidth: 2 }} />
                                            AI is generating tasks…
                                        </span>
                                    ) : '✦ Generate Tasks with AI'}
                                </button>
                            )}

                            {/* Manual Tasks Section switch */}
                            {!showTaskSection && (
                                <button className="btn btn-secondary"
                                    onClick={() => { setTaskForm(f => ({ ...f, priority: savedRequirement.priority })); setShowTaskSection(true); }}>
                                    + Add Tasks Manually
                                </button>
                            )}
                        </div>

                        {/* AI Loading state placeholder */}
                        {aiLoading && (
                            <div style={{ marginTop: 16, display: 'flex', flexDirection: 'column', gap: 12, padding: '20px', background: 'var(--color-bg)', borderRadius: 'var(--radius-md)', border: '1px solid var(--color-border)' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: '8px' }}>
                                    <span className="spinner" style={{ width: 20, height: 20, borderColor: '#6366f1', borderRightColor: 'transparent' }} />
                                    <span style={{ color: '#6366f1', fontWeight: 600 }}>AI is generating tasks… Please wait 10-20 seconds.</span>
                                </div>
                                <div className="skeleton" style={{ height: 24, width: '100%' }} />
                                <div className="skeleton" style={{ height: 24, width: '80%' }} />
                                <div className="skeleton" style={{ height: 24, width: '90%' }} />
                            </div>
                        )}

                        {/* AI Network Failures alerts */}
                        {aiError && (
                            <div style={{ marginTop: 12, padding: '10px 14px', background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 8, color: '#dc2626', fontSize: 13 }}>
                                ⚠️ {aiError}
                            </div>
                        )}
                    </div>
                ) : (
                    <>
                        {/* Project selector */}
                        <div className="form-group">
                            <label className="form-label">Project <span className="required">*</span></label>
                            {loadingProjects ? (
                                <div className="spinner" style={{ width: 20, height: 20 }} />
                            ) : projects.length === 0 ? (
                                <p className="form-error">No projects found. Create one first from the Projects page.</p>
                            ) : (
                                <select className="form-input" value={reqForm.project_id}
                                    onChange={e => { setReqForm(f => ({ ...f, project_id: e.target.value })); setReqErrors(er => ({ ...er, project_id: '' })); }}>
                                    {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                                </select>
                            )}
                            {reqErrors.project_id && <p className="form-error">{reqErrors.project_id}</p>}
                        </div>

                        {/* Title input */}
                        <div className="form-group">
                            <label className="form-label">Requirement Title <span className="required">*</span></label>
                            <input className="form-input" type="text"
                                value={reqForm.title}
                                onChange={e => { setReqForm(f => ({ ...f, title: e.target.value })); setReqErrors(er => ({ ...er, title: '' })); }}
                                placeholder="e.g. User authentication flow"
                            />
                            {reqErrors.title && <p className="form-error">{reqErrors.title}</p>}
                        </div>

                        {/* Description textarea */}
                        <div className="form-group">
                            <label className="form-label">Description <span className="required">*</span></label>
                            <textarea className="form-input" rows={4}
                                value={reqForm.description}
                                onChange={e => { setReqForm(f => ({ ...f, description: e.target.value })); setReqErrors(er => ({ ...er, description: '' })); }}
                                placeholder="Describe what this requirement covers and why it's needed…"
                            />
                            {reqErrors.description && <p className="form-error">{reqErrors.description}</p>}
                        </div>

                        {/* Priority Selector */}
                        <div className="form-group" style={{ maxWidth: 240 }}>
                            <label className="form-label">Priority <span className="required">*</span></label>
                            <select className="form-input" value={reqForm.priority}
                                onChange={e => { setReqForm(f => ({ ...f, priority: e.target.value })); setReqErrors(er => ({ ...er, priority: '' })); }}>
                                {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                            </select>
                            {reqErrors.priority && <p className="form-error">{reqErrors.priority}</p>}
                        </div>

                        {/* Acceptance Criteria criteria */}
                        <div className="form-group">
                            <label className="form-label">Acceptance Criteria / Expected Output</label>
                            <textarea className="form-input" rows={3}
                                value={reqForm.acceptance_criteria}
                                onChange={e => setReqForm(f => ({ ...f, acceptance_criteria: e.target.value }))}
                                placeholder="Optional: define what 'DONE' looks like for this requirement…"
                            />
                        </div>

                        {reqErrors.form && <p className="form-error" style={{ marginBottom: 12 }}>{reqErrors.form}</p>}
                        {reqMsg && <p style={{ color: '#16a34a', fontSize: 13, marginBottom: 12 }}>✓ {reqMsg}</p>}

                        {/* Submit Actions row */}
                        <div className="form-actions-row">
                            <button className="btn btn-primary btn-glow" disabled={reqSubmitting}
                                onClick={saveAndGenerateAI}
                                style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', border: 'none' }}>
                                {reqSubmitting ? 'Saving…' : '✦ Generate AI Tasks'}
                            </button>
                            <button className="btn btn-secondary" disabled={reqSubmitting}
                                onClick={() => saveRequirement(true)}>
                                {reqSubmitting ? 'Saving…' : 'Save & Add Tasks Manually'}
                            </button>
                            <button className="btn btn-secondary" disabled={reqSubmitting}
                                onClick={() => saveRequirement(false)}
                                style={{ opacity: 0.7 }}>
                                {reqSubmitting ? 'Saving…' : 'Save Requirement'}
                            </button>
                        </div>
                    </>
                )}
            </div>

            {/* ── SECTION AI: AI Suggestion Review Panel ── */}
            {showAIReview && aiTasks.length > 0 && savedRequirement && (
                <div className="ai-premium-card" style={{ marginBottom: '24px' }}>
                    <div style={{ background: 'var(--color-surface)', borderRadius: 'calc(var(--radius-md) - 2px)', padding: '24px' }}>
                        <div className="card-header">
                            <h3 className="card-title" style={{ color: '#6366f1' }}>
                                ✦ AI-Generated Tasks — Review & Edit
                            </h3>
                            <p className="muted-sm" style={{ marginTop: 4 }}>
                                {aiSummary && <><strong>AI Summary:</strong> {aiSummary}<br /></>}
                                Review the tasks below. You can edit any field, remove tasks, or add assignees before confirming.
                            </p>
                        </div>

                        {/* Suggestions table */}
                        <div className="task-table-wrapper" style={{ overflowX: 'auto' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                                <thead>
                                    <tr style={{ borderBottom: '2px solid #e2e8f0', textAlign: 'left' }}>
                                        <th style={{ padding: '8px 6px', fontWeight: 600 }}>#</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, minWidth: 180 }}>Title</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, minWidth: 100 }}>Type</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, minWidth: 100 }}>Priority</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, minWidth: 80 }}>Effort</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, minWidth: 150 }}>Assignee</th>
                                        <th style={{ padding: '8px 6px', fontWeight: 600, width: 60 }}>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {aiTasks.map((task, idx) => (
                                        <tr key={idx} style={{ borderBottom: '1px solid #f1f5f9', cursor: 'pointer' }}
                                            onClick={() => { setEditingTaskIndex(idx); setEditingTaskData({ ...task }); }}
                                            title="Click to view details"
                                        >
                                            <td style={{ padding: '8px 6px', color: '#94a3b8' }}>{idx + 1}</td>
                                            <td style={{ padding: '8px 6px', fontWeight: '500' }}>{task.title}</td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <span style={{ fontSize: 12, background: '#f1f5f9', padding: '2px 6px', borderRadius: 4 }}>
                                                    {task.task_type}
                                                </span>
                                            </td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <span className={`badge ${priorityClass(task.priority)}`}>{task.priority}</span>
                                            </td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <span style={{ fontSize: 12, fontWeight: 600 }}>{task.effort_points}</span>
                                            </td>
                                            <td style={{ padding: '8px 6px', fontSize: 13 }}>
                                                {task.assignee_id ? teamUsers.find(u => u.id === parseInt(task.assignee_id))?.name || 'Unknown' : <span style={{ color: '#94a3b8' }}>Unassigned</span>}
                                            </td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <button
                                                    className="btn btn-sm"
                                                    onClick={(e) => { e.stopPropagation(); handleRemoveAITask(idx); }}
                                                    style={{ color: '#dc2626', background: 'transparent', border: '1px solid #fecaca', padding: '3px 8px', fontSize: 12 }}
                                                    title="Remove this task"
                                                >
                                                    ✕
                                                </button>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>

                        {/* In-place edit modal for a selected AI suggestion */}
                        {editingTaskIndex !== null && editingTaskData && (
                            <div className="overlay" onClick={() => setEditingTaskIndex(null)}>
                                <div className="card" onClick={e => e.stopPropagation()} style={{ width: '90vw', maxWidth: 600, maxHeight: '85vh', overflowY: 'auto' }}>
                                    <div className="card-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                                        <h3 className="card-title">Task Details</h3>
                                        <button className="btn btn-sm" style={{ background: 'transparent', border: 'none', color: '#64748b', fontSize: 20, padding: 0 }} onClick={() => setEditingTaskIndex(null)}>✕</button>
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Title <span className="required">*</span></label>
                                        <input className="form-input" type="text" value={editingTaskData.title}
                                            onChange={e => setEditingTaskData({ ...editingTaskData, title: e.target.value })}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Description</label>
                                        <textarea className="form-input" rows={2} value={editingTaskData.description}
                                            onChange={e => setEditingTaskData({ ...editingTaskData, description: e.target.value })}
                                        />
                                    </div>
                                    <div className="form-grid-2">
                                        <div className="form-group">
                                            <label className="form-label">Task Type <span className="required">*</span></label>
                                            <select className="form-input" value={editingTaskData.task_type}
                                                onChange={e => setEditingTaskData({ ...editingTaskData, task_type: e.target.value })}>
                                                {TASK_TYPE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                            </select>
                                        </div>
                                        <div className="form-group">
                                            <label className="form-label">Priority <span className="required">*</span></label>
                                            <select className="form-input" value={editingTaskData.priority}
                                                onChange={e => setEditingTaskData({ ...editingTaskData, priority: e.target.value })}>
                                                {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                            </select>
                                        </div>
                                    </div>
                                    <div className="form-grid-2">
                                        <div className="form-group">
                                            <label className="form-label">Effort Points <span className="required">*</span></label>
                                            <select className="form-input" value={editingTaskData.effort_points}
                                                onChange={e => setEditingTaskData({ ...editingTaskData, effort_points: Number(e.target.value) })}>
                                                {EFFORT_OPTIONS.map(ep => <option key={ep} value={ep}>{ep}</option>)}
                                            </select>
                                        </div>
                                        <div className="form-group">
                                            <label className="form-label">Assignee</label>
                                            <select className="form-input" value={editingTaskData.assignee_id || ''}
                                                onChange={e => setEditingTaskData({ ...editingTaskData, assignee_id: e.target.value || null })}>
                                                <option value="">Unassigned</option>
                                                {teamUsers.map(u => (
                                                    <option key={u.id} value={u.id}>
                                                        {u.name} ({u.role_id === 3 ? 'Dev' : 'Tester'})
                                                    </option>
                                                ))}
                                            </select>
                                        </div>
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Acceptance Criteria</label>
                                        <textarea className="form-input" rows={2} value={editingTaskData.acceptance_criteria}
                                            onChange={e => setEditingTaskData({ ...editingTaskData, acceptance_criteria: e.target.value })}
                                        />
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label">Possible Risks</label>
                                        <textarea className="form-input" rows={2} value={editingTaskData.possible_risks}
                                            onChange={e => setEditingTaskData({ ...editingTaskData, possible_risks: e.target.value })}
                                        />
                                    </div>
                                    <div className="form-actions-row" style={{ marginTop: 20 }}>
                                        <button className="btn btn-primary" onClick={() => {
                                            const newTasks = [...aiTasks];
                                            newTasks[editingTaskIndex] = editingTaskData;
                                            setAiTasks(newTasks);
                                            setEditingTaskIndex(null);
                                        }}>Save Changes</button>
                                        <button className="btn btn-secondary" onClick={() => setEditingTaskIndex(null)}>Close</button>
                                    </div>
                                </div>
                            </div>
                        )}

                        {aiConfirmError && <p className="form-error" style={{ marginTop: 12 }}>{aiConfirmError}</p>}

                        {/* Confirmation Actions */}
                        <div className="form-actions-row" style={{ marginTop: 16 }}>
                            <button className="btn btn-primary" disabled={aiConfirming}
                                onClick={handleConfirmAITasks}
                                style={{ background: 'linear-gradient(135deg, #16a34a, #15803d)', border: 'none' }}>
                                {aiConfirming ? 'Saving…' : `✓ Confirm and Save ${aiTasks.length} Tasks to Backlog`}
                            </button>
                            <button className="btn btn-secondary" disabled={aiConfirming}
                                onClick={() => handleGenerateAI()}>
                                ↻ Regenerate with AI
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* ── AI CONFIRMATION SUCCESS ALERT ── */}
            {aiSavedTasks.length > 0 && (
                <div className="card" style={{ borderLeft: '4px solid #16a34a' }}>
                    <div className="card-header">
                        <h3 className="card-title" style={{ color: '#16a34a' }}>
                            ✅ {aiConfirmMsg}
                        </h3>
                    </div>
                    <ul className="item-list">
                        {aiSavedTasks.map((t, i) => (
                            <li key={t.id || i} className="item-row">
                                <strong className="item-name">{t.title}</strong>
                            </li>
                        ))}
                    </ul>
                    <div style={{ marginTop: 12, display: 'flex', gap: 10 }}>
                        <Link to={`/backlog`} className="btn btn-primary" style={{ textDecoration: 'none' }}>
                            → Go to Backlog
                        </Link>
                        <button className="btn btn-secondary" onClick={() => navigate('/dashboard')}>
                            Go to Dashboard
                        </button>
                    </div>
                </div>
            )}

            {/* ── STEP 2: Manual Task Creator Panel ── */}
            {showTaskSection && savedRequirement && (
                <div className="card">
                    <div className="card-header">
                        <h3 className="card-title">Add Tasks Manually</h3>
                        <p className="muted-sm" style={{ marginTop: 4 }}>
                            Requirement: <strong>{savedRequirement.title}</strong> ·
                            Priority inherited as default — change per task as needed.
                        </p>
                    </div>

                    <form onSubmit={handleAddTask}>
                        <div className="form-group">
                            <label className="form-label">Task Title <span className="required">*</span></label>
                            <input className="form-input" type="text"
                                value={taskForm.title}
                                onChange={e => { setTaskForm(f => ({ ...f, title: e.target.value })); setTaskErrors(er => ({ ...er, title: '' })); }}
                                placeholder="e.g. Build login endpoint"
                            />
                            {taskErrors.title && <p className="form-error">{taskErrors.title}</p>}
                        </div>

                        <div className="form-group">
                            <label className="form-label">Description</label>
                            <textarea className="form-input" rows={2}
                                value={taskForm.description}
                                onChange={e => setTaskForm(f => ({ ...f, description: e.target.value }))}
                                placeholder="Optional task notes…"
                            />
                        </div>

                        <div className="form-grid-2">
                            <div className="form-group">
                                <label className="form-label">Task Type <span className="required">*</span></label>
                                <select className="form-input" value={taskForm.task_type}
                                    onChange={e => { setTaskForm(f => ({ ...f, task_type: e.target.value })); setTaskErrors(er => ({ ...er, task_type: '' })); }}>
                                    {TASK_TYPE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                </select>
                                {taskErrors.task_type && <p className="form-error">{taskErrors.task_type}</p>}
                            </div>
                            <div className="form-group">
                                <label className="form-label">Priority <span className="required">*</span></label>
                                <select className="form-input" value={taskForm.priority}
                                    onChange={e => { setTaskForm(f => ({ ...f, priority: e.target.value })); setTaskErrors(er => ({ ...er, priority: '' })); }}>
                                    {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                </select>
                                <p className="muted-sm" style={{ marginTop: 3 }}>Prefilled from requirement — change as needed.</p>
                                {taskErrors.priority && <p className="form-error">{taskErrors.priority}</p>}
                            </div>
                        </div>

                        <div className="form-grid-2">
                            <div className="form-group">
                                <label className="form-label">Sprint (optional)</label>
                                <select className="form-input" value={taskForm.sprint_id}
                                    onChange={e => setTaskForm(f => ({ ...f, sprint_id: e.target.value }))}>
                                    <option value="">— No sprint (Backlog) —</option>
                                    {sprints.map(s => (
                                        <option key={s.id} value={s.id}>
                                            {s.name} ({s.status})
                                        </option>
                                    ))}
                                </select>
                            </div>
                            <div className="form-group">
                                <label className="form-label">Assignee</label>
                                <select className="form-input" value={taskForm.assignee_id}
                                    onChange={e => setTaskForm(f => ({ ...f, assignee_id: e.target.value }))}>
                                    <option value="">Unassigned</option>
                                    {teamUsers.map(u => (
                                        <option key={u.id} value={u.id}>
                                            {u.name} ({u.role_id === 3 ? 'Developer' : 'Tester'})
                                        </option>
                                    ))}
                                </select>
                            </div>
                        </div>

                        <div className="form-grid-2">
                            <div className="form-group">
                                <label className="form-label">Due Date</label>
                                <input className="form-input" type="date"
                                    value={taskForm.due_date}
                                    onChange={e => setTaskForm(f => ({ ...f, due_date: e.target.value }))}
                                />
                            </div>
                            <div className="form-group">
                                <label className="form-label">Estimated Hours</label>
                                <input className="form-input" type="number" step="0.5" min="0"
                                    value={taskForm.estimated_hours}
                                    onChange={e => setTaskForm(f => ({ ...f, estimated_hours: e.target.value }))}
                                    placeholder="e.g. 4"
                                />
                            </div>
                        </div>

                        <p className="muted-sm" style={{ marginBottom: 12 }}>
                            Requirement: <strong>{savedRequirement.title}</strong> ·
                            Project: <strong>{projects.find(p => p.id === savedRequirement.project_id)?.name}</strong> ·
                            Status: <span className="badge badge-todo">todo</span>
                        </p>

                        {taskErrors.form && <p className="form-error" style={{ marginBottom: 10 }}>{taskErrors.form}</p>}
                        {taskMsg && <p style={{ color: '#16a34a', fontSize: 13, marginBottom: 10 }}>✓ {taskMsg}</p>}

                        <div className="form-actions-row">
                            <button type="submit" className="btn btn-primary" disabled={taskSubmitting}>
                                {taskSubmitting ? 'Adding…' : '+ Add Task'}
                            </button>
                            <button type="button" className="btn btn-secondary"
                                onClick={() => navigate('/dashboard')}>
                                Done — Go to Dashboard
                            </button>
                        </div>
                    </form>

                    {/* Manual tasks added in this active session */}
                    {createdTasks.length > 0 && (
                        <>
                            <div className="section-divider" style={{ margin: '20px 0 16px' }} />
                            <h4 className="card-title" style={{ marginBottom: 12 }}>
                                Tasks added this session ({createdTasks.length})
                            </h4>
                            <ul className="item-list">
                                {createdTasks.map((t, i) => (
                                    <li key={t?.id || i} className="item-row">
                                        <div>
                                            <strong className="item-name">{t?.title || `Task ${i + 1}`}</strong>
                                            <p className="muted-sm" style={{ marginTop: 2 }}>
                                                {t?.task_type} · {t?.project_name ? `Project: ${t.project_name}` : 'Unknown Project'} · {t?.sprint_name ? `Sprint: ${t.sprint_name}` : 'Backlog'}
                                            </p>
                                        </div>
                                        <span className={`badge ${priorityClass(t?.priority)}`}>{t?.priority}</span>
                                    </li>
                                ))}
                            </ul>
                        </>
                    )}
                </div>
            )}
        </div>
    );
}
