import React, { useState, useEffect } from 'react';
import { getProjects } from '../api/projects';
import { getRequirements, updateRequirementStatus, updateRequirement, deleteRequirement } from '../api/requirements';
import { generateTaskBreakdown, confirmAITasks } from '../api/ai';
import { getTeamUsers } from '../api/auth';
import { priorityClass, formatDate, getErrorMessage, getUser } from '../utils/helpers';
import { TASK_TYPE_OPTIONS, EFFORT_OPTIONS, PRIORITY_OPTIONS } from '../utils/constants';

/**
 * RequirementsPage Component
 * --------------------------------------------------------------------------------
 * Displays requirements registered under a selected project.
 * For requirements in 'DRAFT' status, users can invoke an AI assistant to break down
 * the requirement description into discrete tasks, review them, edit attributes,
 * assign team members, and save them directly to the backlog.
 * --------------------------------------------------------------------------------
 */
export default function RequirementsPage() {
    // State variables
    const [projects, setProjects] = useState([]);                  // Complete list of projects in system
    const [selectedProjectId, setSelectedProjectId] = useState(''); // Selected project ID filter
    const [requirements, setRequirements] = useState([]);          // List of requirements matching selected project
    const [loading, setLoading] = useState(false);                  // Requirements spinner loader
    const [teamUsers, setTeamUsers] = useState([]);                  // List of team users (for assignees selectors)

    // AI task generator states
    const [aiLoading, setAiLoading] = useState(false);              // AI request loading indicator
    const [aiError, setAiError] = useState('');                      // AI generator network error details
    const [aiTasks, setAiTasks] = useState([]);                      // Array of tasks generated by the AI
    const [aiSuggestionId, setAiSuggestionId] = useState(null);      // Suggestion ID returned by AI engine for confirmation tracking
    const [aiSummary, setAiSummary] = useState('');                  // Summarized description of breakdown from AI
    const [showAIReview, setShowAIReview] = useState(false);        // Toggle for displaying AI review modal
    const [aiConfirming, setAiConfirming] = useState(false);        // Indicator while saving confirmed AI tasks
    const [aiConfirmError, setAiConfirmError] = useState('');        // Confirm/save errors
    const [currentReqForAI, setCurrentReqForAI] = useState(null);    // Reference to the active requirement being broken down

    // Modal state for editing individual AI generated tasks
    const [editingTaskIndex, setEditingTaskIndex] = useState(null);  // Index in the tasks list being edited
    const [editingTaskData, setEditingTaskData] = useState(null);    // Buffer state containing task details being edited

    // User check & requirement editing states
    const currentUser = getUser();
    const isPmOrAdmin = currentUser?.role_id === 1 || currentUser?.role_id === 2;
    const [editingRequirement, setEditingRequirement] = useState(null);
    const [editForm, setEditForm] = useState({ title: '', description: '', priority: 'medium', acceptance_criteria: '' });
    const [editErrors, setEditErrors] = useState({});
    const [editSubmitting, setEditSubmitting] = useState(false);

    // Initial page load data fetching
    useEffect(() => {
        // Fetch projects list
        getProjects().then(res => {
            const projs = res.data?.data || [];
            setProjects(projs);
            // Default select the first project if listings are not empty
            if (projs.length > 0) {
                setSelectedProjectId(String(projs[0].id));
            }
        }).catch(err => console.error(err));
        
        // Fetch users list
        getTeamUsers().then(res => {
            setTeamUsers(res.data?.data || []);
        }).catch(err => console.error(err));
    }, []);

    // Reload requirements whenever the selected project changes
    useEffect(() => {
        if (!selectedProjectId) {
            setRequirements([]);
            return;
        }
        fetchRequirements(selectedProjectId);
    }, [selectedProjectId]);

    /**
     * fetchRequirements Function
     * Invokes GET router to fetch project specific requirements.
     */
    async function fetchRequirements(projectId) {
        setLoading(true);
        try {
            const res = await getRequirements({ project_id: projectId });
            setRequirements(res.data?.data || []);
        } catch (err) {
            console.error(err);
        } finally {
            setLoading(false);
        }
    }

    /**
     * handleGenerateAI Function
     * Sends requirement title, description, and acceptance criteria to the AI breakdown engine.
     * Parses the resulting tasks list and opens the review modal overlay.
     */
    async function handleGenerateAI(req) {
        setCurrentReqForAI(req);
        setAiLoading(true);
        setAiError('');
        setAiTasks([]);
        setShowAIReview(false);
        setAiConfirmError('');

        try {
            const res = await generateTaskBreakdown({
                requirement_id: req.id,
                requirement_title: req.title,
                requirement_description: req.description,
                expected_output: req.acceptance_criteria || null,
            });

            const data = res.data?.data;
            setAiSuggestionId(data.suggestion_id);
            setAiSummary(data.summary || '');
            setAiTasks(data.tasks || []);
            setShowAIReview(true);
        } catch (err) {
            setAiError(getErrorMessage(err) || 'AI is currently unavailable.');
            setCurrentReqForAI(null);
        } finally {
            setAiLoading(false);
        }
    }

    /**
     * handleRemoveAITask Function
     * Removes a task from the local temporary AI list before confirming.
     */
    function handleRemoveAITask(index) {
        setAiTasks(prev => prev.filter((_, i) => i !== index));
    }

    /**
     * handleConfirmAITasks Function
     * Submits the reviewed/edited AI tasks list, updates the parent requirement status
     * to 'TASKS_CREATED', and reloads page lists.
     */
    async function handleConfirmAITasks() {
        if (aiTasks.length === 0) {
            setAiConfirmError('No tasks to save.');
            return;
        }

        setAiConfirming(true);
        setAiConfirmError('');

        try {
            // 1. Confirm AI tasks in the database backlog
            await confirmAITasks({
                suggestion_id: aiSuggestionId,
                sprint_id: null, // Saved directly to backlog first
                tasks: aiTasks.map(t => ({
                    title: t.title,
                    description: t.description || null,
                    task_type: t.task_type,
                    priority: t.priority,
                    effort_points: t.effort_points ? Number(t.effort_points) : null,
                    acceptance_criteria: t.acceptance_criteria || null,
                    possible_risks: t.possible_risks || null,
                    assignee_id: t.assignee_id ? Number(t.assignee_id) : null,
                    status: 'TODO',
                })),
            });

            // 2. Update requirement status from DRAFT to TASKS_CREATED
            await updateRequirementStatus(currentReqForAI.id, 'TASKS_CREATED');
            
            // 3. Refresh lists
            await fetchRequirements(selectedProjectId);

            // Reset modal states on success
            setShowAIReview(false);
            setCurrentReqForAI(null);
            alert('Tasks generated and saved to backlog successfully!');
        } catch (err) {
            setAiConfirmError(getErrorMessage(err));
        } finally {
            setAiConfirming(false);
        }
    }

    /**
     * handleEditRequirement Function
     * Pre-populates the edit form and opens the edit modal overlay.
     */
    function handleEditRequirement(req) {
        setEditingRequirement(req);
        setEditForm({
            title: req.title,
            description: req.description,
            priority: req.priority,
            acceptance_criteria: req.acceptance_criteria || '',
        });
        setEditErrors({});
    }

    /**
     * handleSaveRequirement Function
     * Validates and submits the updated requirement details to the backend.
     */
    async function handleSaveRequirement(e) {
        if (e) e.preventDefault();
        
        // Frontend validation
        const errors = {};
        if (!editForm.title.trim()) errors.title = 'Title is required.';
        if (!editForm.description.trim()) errors.description = 'Description is required.';
        if (Object.keys(errors).length > 0) {
            setEditErrors(errors);
            return;
        }

        setEditSubmitting(true);
        try {
            await updateRequirement(editingRequirement.id, {
                title: editForm.title.trim(),
                description: editForm.description.trim(),
                priority: editForm.priority,
                acceptance_criteria: editForm.acceptance_criteria.trim() || null,
            });
            await fetchRequirements(selectedProjectId);
            setEditingRequirement(null);
        } catch (err) {
            setEditErrors({ form: getErrorMessage(err) });
        } finally {
            setEditSubmitting(false);
        }
    }

    /**
     * handleDeleteRequirement Function
     * Prompts for confirmation and deletes the requirement.
     */
    async function handleDeleteRequirement(req) {
        const confirmed = window.confirm(
            `Are you sure you want to delete requirement "REQ-${req.id}: ${req.title}"?\n\n` +
            `This will remove any AI suggestion history. Associated backlog tasks will remain but lose their requirement link.`
        );
        if (!confirmed) return;

        try {
            await deleteRequirement(req.id);
            await fetchRequirements(selectedProjectId);
        } catch (err) {
            alert(getErrorMessage(err));
        }
    }

    return (
        <div className="page page-wide">
            {/* Page Header */}
            <div className="page-header">
                <h1 className="page-title">Requirements</h1>
                <p className="muted-sm" style={{ marginTop: 4 }}>
                    Manage and view saved requirements for a project.
                </p>
            </div>

            {/* Project Filter Selector */}
            <div className="form-group" style={{ maxWidth: 300, marginBottom: 20 }}>
                <label className="form-label">Select Project</label>
                <select className="form-input" value={selectedProjectId}
                    onChange={e => setSelectedProjectId(e.target.value)}>
                    <option value="">— Select a Project —</option>
                    {projects.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}
                </select>
            </div>

            {/* Skeletons vs Requirements Table rendering */}
            {loading ? (
                <div className="spinner" style={{ margin: '40px auto' }} />
            ) : requirements.length === 0 ? (
                <div className="card">
                    <div className="empty-state">
                        <p>No requirements found for this project.</p>
                    </div>
                </div>
            ) : (
                <div className="card" style={{ padding: 0, overflow: 'hidden' }}>
                    <div className="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Title</th>
                                    <th>Priority</th>
                                    <th>Status</th>
                                    <th>Created Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                {requirements.map(req => (
                                    <tr key={req.id}>
                                        <td>REQ-{req.id}</td>
                                        <td style={{ fontWeight: 500 }}>{req.title}</td>
                                        <td>
                                            <span className={`badge ${priorityClass(req.priority)}`}>{req.priority}</span>
                                        </td>
                                        <td>
                                            <span className="badge" style={{ backgroundColor: req.status === 'DRAFT' ? '#fef3c7' : '#dcfce3', color: req.status === 'DRAFT' ? '#92400e' : '#166534' }}>
                                                {req.status}
                                            </span>
                                        </td>
                                        <td>{formatDate(req.created_at)}</td>
                                        <td>
                                            <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                                                {/* AI Breakdown trigger button shown only for DRAFT requirements */}
                                                {req.status === 'DRAFT' ? (
                                                    <button 
                                                        className="btn btn-sm btn-primary"
                                                        style={{ background: 'linear-gradient(135deg, #6366f1, #8b5cf6)', border: 'none' }}
                                                        onClick={() => handleGenerateAI(req)}
                                                        disabled={aiLoading}
                                                    >
                                                        {aiLoading && currentReqForAI?.id === req.id ? 'Generating...' : '✦ Generate AI Tasks'}
                                                    </button>
                                                ) : (
                                                    <button className="btn btn-sm btn-secondary" onClick={() => window.location.href='/backlog'}>
                                                        View Tasks (Backlog)
                                                    </button>
                                                )}

                                                {/* PM / Admin only Edit/Delete actions */}
                                                {isPmOrAdmin && (
                                                    <>
                                                        <button
                                                            className="btn btn-secondary btn-sm"
                                                            onClick={() => handleEditRequirement(req)}
                                                            title="Edit requirement"
                                                        >
                                                            ✏️ Edit
                                                        </button>
                                                        <button
                                                            className="btn btn-sm"
                                                            style={{ background: '#fee2e2', color: '#dc2626' }}
                                                            onClick={() => handleDeleteRequirement(req)}
                                                            title="Delete requirement"
                                                        >
                                                            🗑️ Delete
                                                        </button>
                                                    </>
                                                )}
                                            </div>
                                        </td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </div>
            )}

            {/* ── AI Task Review Modal Overlay ── */}
            {showAIReview && aiTasks.length > 0 && currentReqForAI && (
                <div className="modal-backdrop">
                    <div className="modal" style={{ maxWidth: 900, width: '90vw', maxHeight: '90vh', display: 'flex', flexDirection: 'column' }}>
                        <div className="modal-header">
                            <h3 className="modal-title" style={{ color: '#6366f1' }}>
                                ✦ AI-Generated Tasks for: {currentReqForAI.title}
                            </h3>
                            <p className="muted-sm" style={{ marginTop: 4 }}>
                                {aiSummary && <><strong>Summary:</strong> {aiSummary}<br /></>}
                                Review and edit tasks before saving.
                            </p>
                        </div>

                        <div className="modal-body" style={{ flex: 1, overflowY: 'auto' }}>
                            {aiError && (
                                <div style={{ marginBottom: 12, padding: '10px 14px', background: '#fef2f2', border: '1px solid #fecaca', borderRadius: 8, color: '#dc2626', fontSize: 13 }}>
                                    ⚠️ {aiError}
                                </div>
                            )}
                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
                                <thead>
                                    <tr style={{ borderBottom: '2px solid #e2e8f0', textAlign: 'left' }}>
                                        <th style={{ padding: '8px 6px' }}>Title</th>
                                        <th style={{ padding: '8px 6px' }}>Type</th>
                                        <th style={{ padding: '8px 6px' }}>Priority</th>
                                        <th style={{ padding: '8px 6px' }}>Effort</th>
                                        <th style={{ padding: '8px 6px' }}>Assignee</th>
                                        <th style={{ padding: '8px 6px', width: 60 }}>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {aiTasks.map((task, idx) => (
                                        <tr key={idx} style={{ borderBottom: '1px solid #f1f5f9', cursor: 'pointer' }}
                                            onClick={() => { setEditingTaskIndex(idx); setEditingTaskData({ ...task }); }}
                                            title="Click to view/edit details"
                                        >
                                            <td style={{ padding: '8px 6px', fontWeight: '500' }}>{task.title}</td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <span style={{ fontSize: 12, background: '#f1f5f9', padding: '2px 6px', borderRadius: 4 }}>{task.task_type}</span>
                                            </td>
                                            <td style={{ padding: '8px 6px' }}>
                                                <span className={`badge ${priorityClass(task.priority)}`}>{task.priority}</span>
                                            </td>
                                            <td style={{ padding: '8px 6px', fontWeight: 600 }}>{task.effort_points}</td>
                                            <td style={{ padding: '8px 6px' }}>
                                                {task.assignee_id ? teamUsers.find(u => u.id === parseInt(task.assignee_id))?.name || 'Unknown' : <span className="muted">Unassigned</span>}
                                            </td>
                                            {/* Stop propagation so row edit click doesn't trigger when hitting delete button */}
                                            <td style={{ padding: '8px 6px' }}>
                                                <button
                                                    className="btn btn-sm"
                                                    onClick={(e) => { e.stopPropagation(); handleRemoveAITask(idx); }}
                                                    style={{ color: '#dc2626', background: 'transparent', border: '1px solid #fecaca', padding: '3px 8px' }}
                                                >✕</button>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>

                            {aiConfirmError && <p className="form-error" style={{ marginTop: 12 }}>{aiConfirmError}</p>}
                        </div>

                        <div className="modal-footer" style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
                            <button className="btn btn-secondary" onClick={() => setShowAIReview(false)}>Cancel</button>
                            <button className="btn btn-primary" disabled={aiConfirming}
                                onClick={handleConfirmAITasks}
                                style={{ background: 'linear-gradient(135deg, #16a34a, #15803d)', border: 'none' }}>
                                {aiConfirming ? 'Saving…' : `✓ Confirm and Save ${aiTasks.length} Tasks`}
                            </button>
                        </div>
                    </div>
                </div>
            )}

            {/* ── Inner Modal for Editing a specific AI Task ── */}
            {editingTaskIndex !== null && editingTaskData && (
                <div className="modal-backdrop" style={{ zIndex: 1100 }} onClick={() => setEditingTaskIndex(null)}>
                    <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 600 }}>
                        <div className="modal-header">
                            <h3 className="modal-title">Edit Task</h3>
                        </div>
                        <div className="modal-body">
                            <div className="form-group">
                                <label className="form-label">Title</label>
                                <input className="form-input" value={editingTaskData.title} onChange={e => setEditingTaskData({...editingTaskData, title: e.target.value})} />
                            </div>
                            <div className="form-group">
                                <label className="form-label">Description</label>
                                <textarea className="form-input" rows={2} value={editingTaskData.description} onChange={e => setEditingTaskData({...editingTaskData, description: e.target.value})} />
                            </div>
                            <div className="form-grid-2">
                                <div className="form-group">
                                    <label className="form-label">Type</label>
                                    <select className="form-input" value={editingTaskData.task_type} onChange={e => setEditingTaskData({...editingTaskData, task_type: e.target.value})}>
                                        {TASK_TYPE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label className="form-label">Priority</label>
                                    <select className="form-input" value={editingTaskData.priority} onChange={e => setEditingTaskData({...editingTaskData, priority: e.target.value})}>
                                        {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                    </select>
                                </div>
                            </div>
                            <div className="form-grid-2">
                                <div className="form-group">
                                    <label className="form-label">Effort Points</label>
                                    <select className="form-input" value={editingTaskData.effort_points} onChange={e => setEditingTaskData({...editingTaskData, effort_points: Number(e.target.value)})}>
                                        {EFFORT_OPTIONS.map(ep => <option key={ep} value={ep}>{ep}</option>)}
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label className="form-label">Assignee</label>
                                    <select className="form-input" value={editingTaskData.assignee_id || ''} onChange={e => setEditingTaskData({...editingTaskData, assignee_id: e.target.value || null})}>
                                        <option value="">Unassigned</option>
                                        {teamUsers.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
                                    </select>
                                </div>
                            </div>
                        </div>
                        {/* Save changes to local memory array, does not hit API until main modal confirm is clicked */}
                        <div className="modal-footer" style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
                            <button className="btn btn-secondary" onClick={() => setEditingTaskIndex(null)}>Close</button>
                            <button className="btn btn-primary" onClick={() => {
                                const newTasks = [...aiTasks];
                                newTasks[editingTaskIndex] = editingTaskData;
                                setAiTasks(newTasks);
                                setEditingTaskIndex(null);
                            }}>Save Changes</button>
                        </div>
                    </div>
                </div>
            )}

            {/* ── Edit Requirement Modal Overlay ── */}
            {editingRequirement && (
                <div className="modal-backdrop" style={{ zIndex: 1100 }} onClick={() => setEditingRequirement(null)}>
                    <div className="modal" onClick={e => e.stopPropagation()} style={{ maxWidth: 600 }}>
                        <div className="modal-header">
                            <h3 className="modal-title">Edit Requirement: REQ-{editingRequirement.id}</h3>
                            <button type="button" className="btn btn-sm" style={{ background: 'transparent', border: 'none', color: '#64748b', fontSize: 20, padding: 0 }} onClick={() => setEditingRequirement(null)}>✕</button>
                        </div>
                        <form onSubmit={handleSaveRequirement}>
                            <div className="modal-body">
                                <div className="form-group">
                                    <label className="form-label">Title <span className="required">*</span></label>
                                    <input 
                                        className="form-input" 
                                        type="text"
                                        value={editForm.title} 
                                        onChange={e => {
                                            setEditForm({ ...editForm, title: e.target.value });
                                            setEditErrors({ ...editErrors, title: '' });
                                        }} 
                                    />
                                    {editErrors.title && <p className="form-error">{editErrors.title}</p>}
                                </div>
                                <div className="form-group">
                                    <label className="form-label">Description <span className="required">*</span></label>
                                    <textarea 
                                        className="form-input" 
                                        rows={4} 
                                        value={editForm.description} 
                                        onChange={e => {
                                            setEditForm({ ...editForm, description: e.target.value });
                                            setEditErrors({ ...editErrors, description: '' });
                                        }} 
                                    />
                                    {editErrors.description && <p className="form-error">{editErrors.description}</p>}
                                </div>
                                <div className="form-group" style={{ maxWidth: 240 }}>
                                    <label className="form-label">Priority <span className="required">*</span></label>
                                    <select 
                                        className="form-input" 
                                        value={editForm.priority} 
                                        onChange={e => setEditForm({ ...editForm, priority: e.target.value })}
                                    >
                                        {PRIORITY_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
                                    </select>
                                </div>
                                <div className="form-group">
                                    <label className="form-label">Acceptance Criteria</label>
                                    <textarea 
                                        className="form-input" 
                                        rows={3} 
                                        value={editForm.acceptance_criteria} 
                                        onChange={e => setEditForm({ ...editForm, acceptance_criteria: e.target.value })} 
                                    />
                                </div>
                                {editErrors.form && <p className="form-error" style={{ marginTop: 12 }}>{editErrors.form}</p>}
                            </div>
                            <div className="modal-footer" style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 16 }}>
                                <button type="button" className="btn btn-secondary" onClick={() => setEditingRequirement(null)}>Cancel</button>
                                <button type="submit" className="btn btn-primary" disabled={editSubmitting}>
                                    {editSubmitting ? 'Saving Changes…' : 'Save Changes'}
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            )}
        </div>
    );
}
